// Sample only.
// Put this into kubejs/client_scripts/ when you want matching tooltip and content translations.

ClientEvents.lang('en_us', event => {
  event.addAll({
    'passivestjs.tooltip.join_prefix': '%1$s, %2$s',
    'passivestjs.tooltip.render_effect': '%1$s: %2$s',
    'passivestjs.tooltip.join_requirement': '%1$s, %2$s',
    'block.skilltree.workbench': 'Workbench',
    'recipe.skilltree.workbench_item_bonus': '%s [%s]',
    'item_condition.skilltree.equipment_type.any': 'Equipment',
    'item_condition.skilltree.equipment_type.armor': 'Armor',
    'item_condition.skilltree.equipment_type.axe': 'Axe',
    'item_condition.skilltree.equipment_type.axe.plural': 'Axes',
    'item_condition.skilltree.equipment_type.boots': 'Boots',
    'item_condition.skilltree.equipment_type.bow': 'Bow',
    'item_condition.skilltree.equipment_type.bow.plural': 'Bows',
    'item_condition.skilltree.equipment_type.chestplate': 'Chestplate',
    'item_condition.skilltree.equipment_type.chestplate.plural': 'Chestplates',
    'item_condition.skilltree.equipment_type.crossbow': 'Crossbow',
    'item_condition.skilltree.equipment_type.crossbow.plural': 'Crossbows',
    'item_condition.skilltree.equipment_type.helmet': 'Helmet',
    'item_condition.skilltree.equipment_type.helmet.plural': 'Helmets',
    'item_condition.skilltree.equipment_type.hoe': 'Hoe',
    'item_condition.skilltree.equipment_type.hoe.plural': 'Hoes',
    'item_condition.skilltree.equipment_type.leggings': 'Leggings',
    'item_condition.skilltree.equipment_type.melee_weapon': 'Melee Weapon',
    'item_condition.skilltree.equipment_type.melee_weapon.plural': 'Melee Weapons',
    'item_condition.skilltree.equipment_type.pickaxe': 'Pickaxe',
    'item_condition.skilltree.equipment_type.pickaxe.plural': 'Pickaxes',
    'item_condition.skilltree.equipment_type.ranged_weapon': 'Ranged Weapon',
    'item_condition.skilltree.equipment_type.ranged_weapon.plural': 'Ranged Weapons',
    'item_condition.skilltree.equipment_type.shield': 'Shield',
    'item_condition.skilltree.equipment_type.shield.plural': 'Shields',
    'item_condition.skilltree.equipment_type.shovel': 'Shovel',
    'item_condition.skilltree.equipment_type.shovel.plural': 'Shovels',
    'item_condition.skilltree.equipment_type.sword': 'Sword',
    'item_condition.skilltree.equipment_type.sword.plural': 'Swords',
    'item_condition.skilltree.equipment_type.tool': 'Tool',
    'item_condition.skilltree.equipment_type.tool.plural': 'Tools',
    'item_condition.skilltree.equipment_type.trident': 'Trident',
    'item_condition.skilltree.equipment_type.trident.plural': 'Tridents',
    'item_condition.skilltree.equipment_type.weapon': 'Weapon',
    'item_condition.skilltree.equipment_type.weapon.plural': 'Weapons',
    'skill_bonus.skilltree.more_item_bonuses': 'You can upgrade %s %s additional times using workbench',
    'skill_bonus.skilltree.more_item_bonuses.one': 'You can upgrade %s an additional time using workbench',

    'skill_bonus.kubejs.sample_runtime_bonus': 'gain %1$s',
    'living_condition.kubejs.sample_combat_state.crouching': 'while crouching',
    'living_condition.kubejs.sample_combat_state.underwater': 'while underwater',
    'event_listener.kubejs.sample_attack_or_tick.attack': 'on attack',
    'event_listener.kubejs.sample_attack_or_tick.tick': 'on interval',
    'skill_requirements.kubejs.sample_low_health_requirement': 'requires the player to be below the configured health ratio',
    'kubejs.passivestjs.sample.tree.title': 'Sample Runtime Tree',
    'kubejs.passivestjs.sample.root.title': 'Sample Runtime Root',
    'kubejs.passivestjs.sample.root.desc.0': 'Entry node for the generic custom runtime sample.',
    'kubejs.passivestjs.sample.attack.title': 'Attack Pulse',
    'kubejs.passivestjs.sample.attack.desc.0': 'Applies the configured bonus on attack while the player is crouching.',
    'kubejs.passivestjs.sample.water.title': 'Water Pulse',
    'kubejs.passivestjs.sample.water.desc.0': 'Applies the configured bonus on tick while the player is underwater.',
    'kubejs.passivestjs.sample.requirement.title': 'Last Stand',
    'kubejs.passivestjs.sample.requirement.desc.0': 'A simple custom requirement sample driven by health ratio.',
    'kubejs.passivestjs.sample.socket.title': 'Item Bonus Socket',
    'kubejs.passivestjs.sample.socket.desc.0': 'Guides the workbench item bonus flow instead of putting item bonus data directly on the skill.',
    'kubejs.passivestjs.sample.socket.desc.1': 'Pair this with the workbench recipe sample to socket a shield.',

    'kubejs.passivestjs.sample.chain.tree.title': 'Requirement + Listener Chain',
    'kubejs.passivestjs.sample.chain.root.title': 'Chain Root',
    'kubejs.passivestjs.sample.chain.root.desc.0': 'Root node for the focused requirement/listener sample.',
    'kubejs.passivestjs.sample.chain.skill.title': 'Execution Window',
    'kubejs.passivestjs.sample.chain.skill.desc.0': 'Requires low health before learning.',
    'kubejs.passivestjs.sample.chain.skill.desc.1': 'Then uses the custom attack listener with a nested custom condition.'
  })
})

ClientEvents.lang('zh_cn', event => {
  event.addAll({
    'passivestjs.tooltip.join_prefix': '%1$s、%2$s',
    'passivestjs.tooltip.render_effect': '%1$s：%2$s',
    'passivestjs.tooltip.join_requirement': '%1$s、%2$s',
    'block.skilltree.workbench': '工作台',
    'recipe.skilltree.workbench_item_bonus': '%s [%s]',
    'item_condition.skilltree.equipment_type.any': '装备',
    'item_condition.skilltree.equipment_type.armor': '护甲',
    'item_condition.skilltree.equipment_type.axe': '斧',
    'item_condition.skilltree.equipment_type.axe.plural': '斧',
    'item_condition.skilltree.equipment_type.boots': '靴子',
    'item_condition.skilltree.equipment_type.bow': '弓',
    'item_condition.skilltree.equipment_type.bow.plural': '弓',
    'item_condition.skilltree.equipment_type.chestplate': '胸甲',
    'item_condition.skilltree.equipment_type.chestplate.plural': '胸甲',
    'item_condition.skilltree.equipment_type.crossbow': '弩',
    'item_condition.skilltree.equipment_type.crossbow.plural': '弩',
    'item_condition.skilltree.equipment_type.helmet': '头盔',
    'item_condition.skilltree.equipment_type.helmet.plural': '头盔',
    'item_condition.skilltree.equipment_type.hoe': '锄',
    'item_condition.skilltree.equipment_type.hoe.plural': '锄',
    'item_condition.skilltree.equipment_type.leggings': '护腿',
    'item_condition.skilltree.equipment_type.melee_weapon': '近战武器',
    'item_condition.skilltree.equipment_type.melee_weapon.plural': '近战武器',
    'item_condition.skilltree.equipment_type.pickaxe': '镐',
    'item_condition.skilltree.equipment_type.pickaxe.plural': '镐',
    'item_condition.skilltree.equipment_type.ranged_weapon': '远程武器',
    'item_condition.skilltree.equipment_type.ranged_weapon.plural': '远程武器',
    'item_condition.skilltree.equipment_type.shield': '盾牌',
    'item_condition.skilltree.equipment_type.shield.plural': '盾牌',
    'item_condition.skilltree.equipment_type.shovel': '锹',
    'item_condition.skilltree.equipment_type.shovel.plural': '锹',
    'item_condition.skilltree.equipment_type.sword': '剑',
    'item_condition.skilltree.equipment_type.sword.plural': '剑',
    'item_condition.skilltree.equipment_type.tool': '工具',
    'item_condition.skilltree.equipment_type.tool.plural': '工具',
    'item_condition.skilltree.equipment_type.trident': '三叉戟',
    'item_condition.skilltree.equipment_type.trident.plural': '三叉戟',
    'item_condition.skilltree.equipment_type.weapon': '武器',
    'item_condition.skilltree.equipment_type.weapon.plural': '武器',
    'skill_bonus.skilltree.more_item_bonuses': '你可以使用工作台额外强化 %s %s 次',
    'skill_bonus.skilltree.more_item_bonuses.one': '你可以使用工作台额外强化 %s 一次',

    'skill_bonus.kubejs.sample_runtime_bonus': '获得%1$s',
    'living_condition.kubejs.sample_combat_state.crouching': '在潜行时',
    'living_condition.kubejs.sample_combat_state.underwater': '在水下时',
    'event_listener.kubejs.sample_attack_or_tick.attack': '攻击时',
    'event_listener.kubejs.sample_attack_or_tick.tick': '周期触发时',
    'skill_requirements.kubejs.sample_low_health_requirement': '要求玩家生命值低于配置比例',
    'kubejs.passivestjs.sample.tree.title': '示例运行时技能树',
    'kubejs.passivestjs.sample.root.title': '示例运行时根节点',
    'kubejs.passivestjs.sample.root.desc.0': '通用自定义运行时示例的入口节点。',
    'kubejs.passivestjs.sample.attack.title': '攻击脉冲',
    'kubejs.passivestjs.sample.attack.desc.0': '玩家在潜行攻击时施加配置好的 bonus。',
    'kubejs.passivestjs.sample.water.title': '水下脉冲',
    'kubejs.passivestjs.sample.water.desc.0': '玩家在水下周期性施加配置好的 bonus。',
    'kubejs.passivestjs.sample.requirement.title': '背水一战',
    'kubejs.passivestjs.sample.requirement.desc.0': '一个由生命比例驱动的自定义 requirement 示例。',
    'kubejs.passivestjs.sample.socket.title': '物品 Bonus 插槽',
    'kubejs.passivestjs.sample.socket.desc.0': '这个节点用于引导测试 workbench item bonus 流程，而不是把 item bonus 直接挂在技能上。',
    'kubejs.passivestjs.sample.socket.desc.1': '把它和 workbench recipe 示例配合使用，即可给盾牌打孔。',

    'kubejs.passivestjs.sample.chain.tree.title': 'Requirement 与 Listener 联动',
    'kubejs.passivestjs.sample.chain.root.title': '联动根节点',
    'kubejs.passivestjs.sample.chain.root.desc.0': '用于聚焦 requirement / listener 联动的示例根节点。',
    'kubejs.passivestjs.sample.chain.skill.title': '处决窗口',
    'kubejs.passivestjs.sample.chain.skill.desc.0': '学习前要求生命值较低。',
    'kubejs.passivestjs.sample.chain.skill.desc.1': '学习后使用带有嵌套自定义 condition 的自定义攻击 listener。'
  })
})
