modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="passivestjs"
version="${file.jarVersion}"
displayName="PassiveSTJS"
authors="CrychicTeam-M1hono"
description='''Passive Skill Tree JS bridge mod.'''

[[dependencies.passivestjs]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.passivestjs]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.passivestjs]]
modId="skilltree"
mandatory=true
versionRange="[0.6.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.passivestjs]]
modId="kubejs"
mandatory=true
versionRange="[2001.6.5-build.22,)"
ordering="AFTER"
side="BOTH"

[[dependencies.passivestjs]]
modId="passiveintegration"
mandatory=false
versionRange="[0.1.1,)"
ordering="AFTER"
side="BOTH"
